### ISSUE TITLE
【Ipad Air3】翻译默认从第二行开始显示

### ISSUE THREAD

**Issue by xiaomi2077** [duckbill/marginote-deepl#1]

**Comment by xiaomi2077** [comment]
第一张图：默认显示翻译的第二行
第二张图：完整翻译内容
可能是机型适配问题。。。
![image1](https://user-images.githubusercontent.com/33375652/117016416-44869d00-ad25-11eb-865a-c3bb15e327ab.png)
![image0](https://user-images.githubusercontent.com/33375652/117016426-45b7ca00-ad25-11eb-9068-135df9e9b92a.png)

**Comment by duckbill** [comment]
> 第一张图：默认显示翻译的第二行
> 第二张图：完整翻译内容
> 可能是机型适配问题。。。
> ![image1](https://user-images.githubusercontent.com/33375652/117016416-44869d00-ad25-11eb-865a-c3bb15e327ab.png)
> ![image0](https://user-images.githubusercontent.com/33375652/117016426-45b7ca00-ad25-11eb-9068-135df9e9b92a.png)

您是说翻译的时候deepl并没有翻译权所选中的英文吗？如果是这个问题的话，那应该是deepl自身的问题，可以多试几下，因为我在deepl官网翻译的时候也会碰到翻译不全的时候。

**Comment by xiaomi2077** [comment]
@duckbill deepl翻译全了，插件默认从第2行开始显示。手动下拉能把第一行显示出来，但是会自动跳回初始位置
